let Config = {};
Config.loadImgInterval = 30;
Config.nextPuyosSetCount = 2;
Config.fontHeight = 33;
Config.stageCols = 6;
Config.stageRows = 12;
Config.puyoImgHeight = (window.innerHeight - Config.fontHeight) / Config.stageRows
Config.puyoImgWidth = Config.puyoImgHeight;
Config.freeFallingSpeed = 16;
Config.erasePuyoCount = 4;
Config.eraseAnimationDuration = 30;
Config.puyoColors = 4;
Config.playerFallingSpeed = 0.9;
Config.playerDownSpeed = 15;
Config.playerGroundFrame = 20;
Config.playerMoveFrame = 10;
Config.playerRotateFrame = 10;
Config.zenkeshiDuration = 150;
Config.zenkeshiScore = 3600;
Config.gameOverFrame = 3000;
Config.penaltyUnit = 1000;

